"""
Product Segment Lookup
431 products mapped to 7 segments from ATE's product catalog.
Auto-matches product names typed by sales reps to their segment code.

Legacy note:
Originally used by the older LINE/Python demo path. Still useful as catalog reference.
"""

import re

# Segment full names for display
SEGMENT_NAMES = {
    "CI": "Cable Infrastructure",
    "GET": "General Electrical Testing",
    "LVI": "Low Voltage Installation",
    "MRM": "Motor Reliability Management",
    "PDIX": "Partial Discharge",
    "PP": "Protection & Power",
    "PT": "Power Transformer",
}

# Product model → segment code
# Original product names preserved; matching is done via normalization
_RAW_PRODUCT_SEGMENTS = {
    # === CI — Cable Infrastructure (81 products) ===
    "100kV high voltage tester": "CI",
    "160kV DC high Pot test set": "CI",
    "30kV AC High Voltage Tester": "CI",
    "80kVDCHipot": "CI",
    "AC Hi-Pot Tester": "CI",
    "AC High Voltage Test Set": "CI",
    "AC Hipot": "CI",
    "AC Hipot30kv": "CI",
    "AC/DC Hipot120kV": "CI",
    "AZF 250-CI Flex": "CI",
    "BAKER Surge Tester": "CI",
    "Cable ldentlfier": "CI",
    "CARLOC": "CI",
    "CENTRIX2.0": "CI",
    "CI LCI": "CI",
    "DAC-30": "CI",
    "DC Hipot": "CI",
    "DC&ACHipot": "CI",
    "DCHipot 80kV": "CI",
    "DCHipot 80kVorVLF60kV": "CI",
    "Dielectric Tester 4kVAC": "CI",
    "DigiPHONE": "CI",
    "EASY Thumb": "CI",
    "EASYLOC": "CI",
    "Easyloc system": "CI",
    "EST": "CI",
    "EST-100": "CI",
    "EST35/150": "CI",
    "EST75": "CI",
    "EZ-THUMP": "CI",
    "EZ-Thump 12 kV": "CI",
    "Ferrolux": "CI",
    "Ferrolux Rx": "CI",
    "FLG50-VS": "CI",
    "HIPOT": "CI",
    "HV test set": "CI",
    "HVB10": "CI",
    "Line Radar Tester": "CI",
    "MFM10": "CI",
    "MFT-X1-EVSE Test": "CI",
    "PAS CI": "CI",
    "PD Scan": "CI",
    "PD Scan/UHF PD": "CI",
    "PDIX": "CI",
    "PDProduct": "CI",
    "Piezo": "CI",
    "RCDT310": "CI",
    "SMART THUMP ST25-30": "CI",
    "STX40": "CI",
    "STX40P": "CI",
    "TDM4540": "CI",
    "TDR": "CI",
    "TDR1000/3P": "CI",
    "TDR200/3": "CI",
    "TDR2025": "CI",
    "TDR2050": "CI",
    "TDR2500": "CI",
    "TDR900": "CI",
    "Teleflex": "CI",
    "UHF PD": "CI",
    "UHF PDD": "CI",
    "VLF": "CI",
    "VLF SIN-62-TD/62kV with cable 10M": "CI",
    "VLF Sine 45": "CI",
    "VLF SINE 62 kV": "CI",
    "VLF Sinus 45kV": "CI",
    "VLF Sinus 45kV + TD": "CI",
    "VLF Sinus 45kV or 62kV": "CI",
    "VLF Sinus 62kV": "CI",
    "VLF Sinus 62kV + TAN DELTA": "CI",
    "VLF45 with TD&PD": "CI",
    "VLF45+TD": "CI",
    "VLF45kv": "CI",
    "VLF45kv/62kv": "CI",
    "VLF60kV": "CI",
    "VLF62+TD+PD": "CI",
    "VLF62kV": "CI",
    "VLFSin45kV": "CI",
    "VLFSINE34kV/64kV": "CI",
    "VLFSinus 62kV + TD + PD": "CI",
    "VLFSinus45": "CI",

    # === GET — General Electrical Testing (146 products) ===
    "AVO410": "GET",
    "B10E": "GET",
    "BEFT": "GET",
    "BGFL": "GET",
    "BGFT": "GET",
    "BITE2": "GET",
    "BITE2P": "GET",
    "BITE2P/BITE3": "GET",
    "BITE3": "GET",
    "BITE3 Battery ljmpedance": "GET",
    "BITE5": "GET",
    "BM5200": "GET",
    "BM5200/MIT515": "GET",
    "BT51": "GET",
    "BT51,DLRO10": "GET",
    "BVM": "GET",
    "BVM600": "GET",
    "CB101 Calibration box": "GET",
    "CB832": "GET",
    "CSU20": "GET",
    "CSU20A": "GET",
    "CSU600": "GET",
    "CSU600A": "GET",
    "CSU600AT": "GET",
    "CSU600AT/INGVAR": "GET",
    "DC Hipot 120kV": "GET",
    "DCM300E/DCM305E": "GET",
    "DCM340": "GET",
    "DLR010HD + KC +TL3": "GET",
    "DLRO10": "GET",
    "DLRO10+DH44-C": "GET",
    "DLRO10/10HDX": "GET",
    "DLRO10/10X/10HD": "GET",
    "DLRO10/DLRO10HD": "GET",
    "DLRO100": "GET",
    "DLRO100/MOM200": "GET",
    "DLRO100ESeries": "GET",
    "DLRO100HB": "GET",
    "DLRO100XB": "GET",
    "DLRO10HD": "GET",
    "DLRO10HD + DH4C": "GET",
    "DLRO10HD/10HDX": "GET",
    "DLRO10HD/10X": "GET",
    "DLRO10HD/DLRO10HDX": "GET",
    "DLRO10HDX": "GET",
    "DLRO10X": "GET",
    "DLRO10X+DH4-C": "GET",
    "DLRO10X, DLRO10HD": "GET",
    "DLRO10X/DLRO10HDX": "GET",
    "DLRO2": "GET",
    "DLRO2 + KC100C": "GET",
    "DLRO200": "GET",
    "DLRO200, MOM200A": "GET",
    "DLRO600A": "GET",
    "DLROH200": "GET",
    "DMA35": "GET",
    "DPM1000": "GET",
    "DRLO100EB": "GET",
    "ETK100C": "GET",
    "ETK50": "GET",
    "HPA100AC": "GET",
    "HPA130DC": "GET",
    "INGVAR": "GET",
    "LTW315": "GET",
    "MAGNUS": "GET",
    "Magnus230": "GET",
    "MFT1741": "GET",
    "MIT10125/1525": "GET",
    "MIT1025": "GET",
    "MIT1025+CB101": "GET",
    "MIT1025+CerUKAS": "GET",
    "MIT1025, S1-1068": "GET",
    "MIT1025/1525": "GET",
    "MIT1025/2": "GET",
    "MIT1025/525": "GET",
    "MIT1515": "GET",
    "MIT1525": "GET",
    "MIT1525+CB101": "GET",
    "MIT1525+cer UKAS": "GET",
    "MIT1525+CerUKAS": "GET",
    "MIT1525/2": "GET",
    "MIT320": "GET",
    "MIT400/2, MIT410/2, MIT420/2": "GET",
    "MIT480/2": "GET",
    "MIT515": "GET",
    "MIT515 + Testlead 10 m.": "GET",
    "MIT515,525,1025,1525": "GET",
    "MIT515/1025": "GET",
    "MIT515/2": "GET",
    "MIT515/2, MIT525/2, MIT1025/2": "GET",
    "MIT515/525": "GET",
    "MIT515/BM5200": "GET",
    "MIT525": "GET",
    "MIT525+CB101": "GET",
    "MIT525+CerUKAS": "GET",
    "MIT525, S1-1568": "GET",
    "MIT525/1025": "GET",
    "MIT525/2": "GET",
    "MIT525/MIT1025/MIT1525": "GET",
    "MJOLNER200A": "GET",
    "Mjolner600": "GET",
    "MJOLNER600A": "GET",
    "MJÖLNER200": "GET",
    "MOM2": "GET",
    "MOM2/DLROH200": "GET",
    "MOM2/MOM200/DLRO200": "GET",
    "MOM2/MOM200A": "GET",
    "MOM200/DLRO200": "GET",
    "MOM200A": "GET",
    "MOM200A/DLRO200": "GET",
    "MOM200A/MOM2": "GET",
    "MOM200A/MOM2/DLRO200": "GET",
    "MOM200A/MOM600A": "GET",
    "MOM3": "GET",
    "MOM600A": "GET",
    "MOM600A/200A/2": "GET",
    "MOM690": "GET",
    "MPQ1000": "GET",
    "MPQ2000": "GET",
    "MPRT": "GET",
    "MS-2A": "GET",
    "MTR105": "GET",
    "PAM410": "GET",
    "PAM420": "GET",
    "PSS750": "GET",
    "S1-1068": "GET",
    "S1-1068/ S1-1568": "GET",
    "S1-1568": "GET",
    "S1-1568 / MIT1525": "GET",
    "S1-1586": "GET",
    "S1-568": "GET",
    "SPI225": "GET",
    "TDR1000/3": "GET",
    "TDR2000": "GET",
    "TDR2000/3": "GET",
    "TeleflexSX": "GET",
    "TEST SWITCH": "GET",
    "Torkel900": "GET",
    "Torkel910/930": "GET",
    "Torkel930": "GET",
    "TORKEL930/950": "GET",
    "Torkel950": "GET",
    "TSR1 Plus": "GET",
    "TXL830": "GET",
    "TXL890": "GET",
    "VIDAR": "GET",

    # === LVI — Low Voltage Installation (56 products) ===
    "AVO835": "LVI",
    "CB101": "LVI",
    "DCM1500S": "LVI",
    "DCM300E": "LVI",
    "DCM305": "LVI",
    "DCM320": "LVI",
    "DET14C": "LVI",
    "DET2/3": "LVI",
    "DET24C": "LVI",
    "DET3TC": "LVI",
    "DET3TD": "LVI",
    "DET3TD/TC": "LVI",
    "DET4TCR2": "LVI",
    "DET4TCR2 + Clamps": "LVI",
    "DET4TD": "LVI",
    "DET4TD2": "LVI",
    "DET4TR2": "LVI",
    "DH4-C": "LVI",
    "DTE4TD2": "LVI",
    "EVCA210": "LVI",
    "EVCC300": "LVI",
    "MFT-X1": "LVI",
    "MFT-X1-EVSE": "LVI",
    "MFT1845": "LVI",
    "MIT2500": "LVI",
    "MIT2500-LG1": "LVI",
    "MIT300": "LVI",
    "MIT310": "LVI",
    "MIT320": "LVI",
    "MIT320 / MIT420/2": "LVI",
    "MIT400": "LVI",
    "MIT400/2": "LVI",
    "MIT410": "LVI",
    "MIT410/2": "LVI",
    "MIT410/420": "LVI",
    "MIT420/2": "LVI",
    "MIT420/2LG1": "LVI",
    "MIT430/2": "LVI",
    "MIT430/2 LG1": "LVI",
    "MIT480": "LVI",
    "MIT4xx": "LVI",
    "MPQ1000 , MPQ2000": "LVI",
    "MPU690": "LVI",
    "PAT100": "LVI",
    "PAT120": "LVI",
    "PAT150": "LVI",
    "PAT350": "LVI",
    "PAT350 EU": "LVI",
    "PAT450": "LVI",
    "Phasing tester": "LVI",
    "PMM420": "LVI",
    "RCD330": "LVI",
    "RCDT330": "LVI",
    "TDR1000/3P, TDR2050": "LVI",
    "TDR500/3": "LVI",
    "TPT420": "LVI",

    # === MRM — Motor Reliability Management (8 products) ===
    "ADX": "MRM",
    "ADX15A": "MRM",
    "BAKER DX": "MRM",
    "Baker PPX power pack": "MRM",
    "BAKER PPX30": "MRM",
    "BAKER PPX30 Power Pack": "MRM",
    "EXP400": "MRM",
    "PPX30A": "MRM",

    # === PDIX — Partial Discharge (2 products) ===
    "PD Measurement system": "PDIX",
    "PDIX Product": "PDIX",

    # === PP — Protection & Power (49 products) ===
    "BITE2 or BITE5": "PP",
    "Current Transformer Analyzer": "PP",
    "EGIL": "PP",
    "EGIL Basic": "PP",
    "EGIL wPC": "PP",
    "EGIL/TM1700": "PP",
    "EGIL200": "PP",
    "EGIL221": "PP",
    "EGILBasic": "PP",
    "EgilwithPC": "PP",
    "EGILwithUSB port": "PP",
    "Fraja": "PP",
    "MRCT": "PP",
    "MRCT/MVCT": "PP",
    "MVCT": "PP",
    "ODEN": "PP",
    "ODEN AT": "PP",
    "ODEN AT/3H": "PP",
    "SEVKER780": "PP",
    "SMRT": "PP",
    "SMRT410": "PP",
    "SMRT46": "PP",
    "SMRT46 or SMRT410": "PP",
    "Sverker650": "PP",
    "Sverker750": "PP",
    "Sverker750/780": "PP",
    "SVERKER750/780/900": "PP",
    "SVERKER760": "PP",
    "Sverker780": "PP",
    "SVERKER7xx": "PP",
    "Sverker900": "PP",
    "Sverker900 Basic": "PP",
    "SVERKER900/780/750": "PP",
    "Test Switch (10A-10D-10E-10F-etc)": "PP",
    "TM1700": "PP",
    "TM1700, Egil": "PP",
    "TM1700, EGIL200": "PP",
    "TM1710": "PP",
    "TM1720": "PP",
    "TM1720/1740/1760/1800": "PP",
    "TM1750": "PP",
    "TM1760": "PP",
    "TM1800": "PP",
    "TM200": "PP",
    "TOKEL900 series": "PP",
    "TORKEL 950, TORKEL 910": "PP",
    "TORKEL 950, TXL 865": "PP",
    "Torkel910": "PP",
    "TORKEL950, TORKEL910": "PP",

    # === PT — Power Transformer (89 products) ===
    "CDAX605": "PT",
    "DELTA-4310": "PT",
    "DELTA4000": "PT",
    "Delta4310A": "PT",
    "DGA-G2": "PT",
    "FRAX": "PT",
    "FRAX101": "PT",
    "FRAX99": "PT",
    "G2": "PT",
    "IDAX": "PT",
    "IDAX300": "PT",
    "IDAX300/350": "PT",
    "IDAX322": "PT",
    "IDAX350": "PT",
    "KF-LAB MkII": "PT",
    "KF875": "PT",
    "KF875/KF": "PT",
    "MFT1730": "PT",
    "MIT 515/525/1025": "PT",
    "MIT30": "PT",
    "MIT515/ MIT1025": "PT",
    "MIT525/10125": "PT",
    "MLR10": "PT",
    "MTO106": "PT",
    "MTO210": "PT",
    "MTO250": "PT",
    "MTO300": "PT",
    "MTO310": "PT",
    "MTO330": "PT",
    "MTO330A": "PT",
    "MTO3xx": "PT",
    "MWA300": "PT",
    "MWA300/330": "PT",
    "MWA300/330A": "PT",
    "MWA330A": "PT",
    "Oil purifier": "PT",
    "OIl test Vessel": "PT",
    "OST100AF-USU-X4": "PT",
    "OTD": "PT",
    "OTD LG2 P3": "PT",
    "OTS Stirrer": "PT",
    "OTS100AF": "PT",
    "OTS100AF-USU-P4": "PT",
    "OTS60/80/100": "PT",
    "OTS60/80/100AF": "PT",
    "OTS60AF": "PT",
    "OTS60PB": "PT",
    "OTS60PB/100AF": "PT",
    "OTS60PB/80PB": "PT",
    "OTS60SX/2": "PT",
    "OTS80/100AF": "PT",
    "OTS80AF": "PT",
    "OTS80AF/100AF": "PT",
    "OTS80AF/80PB/100AF": "PT",
    "OTS80PB": "PT",
    "OTS80PB / OTS60PB": "PT",
    "OTS80PB/100AF": "PT",
    "OTS80PB/AF": "PT",
    "PD/PDIX": "PT",
    "TAU3": "PT",
    "TDX120": "PT",
    "TRAX": "PT",
    "TRAX220": "PT",
    "TRAX220+TDX+TSX303": "PT",
    "TRAX279": "PT",
    "TRAX279 with Optional accessories": "PT",
    "TRAX280": "PT",
    "TRAX280 with TSX 303": "PT",
    "TRAX280+TDX+TCX+TSX": "PT",
    "TRAX280+TDX+TSX": "PT",
    "TRAX280/220": "PT",
    "TRAX286": "PT",
    "TRS1": "PT",
    "TSX300": "PT",
    "TTR": "PT",
    "TTR100": "PT",
    "TTR100-1": "PT",
    "TTR1PLUS": "PT",
    "TTR25": "PT",
    "TTR25-1": "PT",
    "TTR300": "PT",
    "TTRU1": "PT",
    "TTRU1/TTRU3": "PT",
    "TTRU3": "PT",
    "TTRU3-PRO/Basic": "PT",
    "TTRU3Basic": "PT",
    "TTRU3Pro": "PT",
    "VCM100D": "PT",
    "VCM80D": "PT",
}


# ---------------------------------------------------------------------------
# Build normalized lookup index
# ---------------------------------------------------------------------------

def _normalize(text):
    """Normalize for matching: lowercase, strip all non-alphanumeric."""
    return re.sub(r'[^a-z0-9]', '', text.lower())


# Pre-built index: normalized_name → segment
_NORMALIZED_INDEX = {}
for _product, _segment in _RAW_PRODUCT_SEGMENTS.items():
    _norm = _normalize(_product)
    if _norm and _norm not in _NORMALIZED_INDEX:
        _NORMALIZED_INDEX[_norm] = _segment


def lookup_segment(product_name):
    """Return segment code (e.g. 'PT') for known products, empty string for others.

    Matches product name against the 431-product catalog.
    Multi-tier matching:
    1. Exact normalized match
    2. Contains match (known model in input, or input in known model)
    3. Token extraction (alphanumeric groups)
    """
    if not product_name:
        return ""

    normalized = _normalize(product_name)
    if not normalized:
        return ""

    # Tier 1: Exact match
    if normalized in _NORMALIZED_INDEX:
        return _NORMALIZED_INDEX[normalized]

    # Tier 2: Contains match — prefer shortest matching key (most specific)
    best_match = None
    best_len = 0
    for model, segment in _NORMALIZED_INDEX.items():
        if model in normalized or normalized in model:
            # Prefer longer matches (more specific)
            if len(model) > best_len:
                best_match = segment
                best_len = len(model)
    if best_match:
        return best_match

    # Tier 3: Extract alphanumeric tokens and try each
    tokens = re.findall(r'[a-z]+\d+[a-z]*|\d+[a-z]+', normalized)
    for token in tokens:
        if token in _NORMALIZED_INDEX:
            return _NORMALIZED_INDEX[token]

    return ""
